# Unfathomably BE
# ----------------
#
# File: signature_negotiation.ex
#
# Purpose:
#   Negotiate RFC 9421 HTTP Message Signatures with ActivityPub peers.
#
# Responsibilities:
#   - publish the exact request components accepted for inbox POSTs
#   - recognize only negotiation requests the local signer can satisfy
#   - remember a successful peer preference for a bounded period
#
# This file intentionally does not parse arbitrary Structured Fields, select
# actor keys, sign requests, or make network requests.

defmodule Pleroma.HTTP.SignatureNegotiation do
  @moduledoc """
  Maintains bounded, per-authority RFC 9421 negotiation state.

  A response `Accept-Signature` field asks the client to sign its next request.
  The preference is therefore keyed by URI authority rather than software name
  or a guessed version. Only the component set generated by the local
  ActivityPub publisher is recognized.
  """

  @cachex Pleroma.Config.get([:cachex, :provider], Cachex)
  @cache :http_signature_format_cache
  @accept_signature ~s|sig1=("@method" "@target-uri" "content-digest");created|
  @compatible_member ~r/(?:\A|,\s*)[a-zA-Z*][a-zA-Z0-9_.*-]*=\("@method" "@target-uri" "content-digest"\);created(?:;alg="(?:rsa-v1_5-sha256|rsa-sha256)")?(?=\s*(?:,|\z))/
  @maximum_header_bytes 2_048

  @spec accept_signature_value() :: String.t()
  def accept_signature_value, do: @accept_signature

  @spec prefers_rfc9421?(String.t()) :: boolean()
  def prefers_rfc9421?(uri) when is_binary(uri) do
    with {:ok, authority} <- authority_key(uri),
         {:ok, true} <- @cachex.get(@cache, authority) do
      true
    else
      _ -> false
    end
  rescue
    _ -> false
  catch
    _, _ -> false
  end

  def prefers_rfc9421?(_uri), do: false

  @spec observe_response(String.t(), term()) :: :ok
  def observe_response(uri, %{status: status, headers: headers})
      when status in 200..299 and is_binary(uri) and is_list(headers) do
    if compatible_response?(headers), do: remember_rfc9421(uri)
    :ok
  end

  def observe_response(_uri, _response), do: :ok

  @spec remember_rfc9421(String.t()) :: :ok
  def remember_rfc9421(uri) when is_binary(uri) do
    with {:ok, authority} <- authority_key(uri) do
      _result = @cachex.put(@cache, authority, true)
    end

    :ok
  rescue
    _ -> :ok
  catch
    _, _ -> :ok
  end

  def remember_rfc9421(_uri), do: :ok

  @spec forget(String.t()) :: :ok
  def forget(uri) when is_binary(uri) do
    with {:ok, authority} <- authority_key(uri) do
      _result = @cachex.del(@cache, authority)
    end

    :ok
  rescue
    _ -> :ok
  catch
    _, _ -> :ok
  end

  def forget(_uri), do: :ok

  defp compatible_response?(headers) do
    headers
    |> Enum.flat_map(fn
      {name, value} when (is_binary(name) or is_atom(name)) and is_binary(value) ->
        if String.downcase(to_string(name)) == "accept-signature", do: [value], else: []

      _header ->
        []
    end)
    |> Enum.any?(&compatible_value?/1)
  end

  defp compatible_value?(value) do
    byte_size(value) <= @maximum_header_bytes and Regex.match?(@compatible_member, value)
  end

  defp authority_key(uri) do
    case URI.parse(uri) do
      %URI{scheme: scheme, host: host, userinfo: nil} = parsed
      when scheme in ["http", "https"] and is_binary(host) and host != "" ->
        port = parsed.port || URI.default_port(scheme)
        {:ok, "#{scheme}://#{String.downcase(host)}:#{port}"}

      _parsed ->
        {:error, :invalid_uri}
    end
  rescue
    URI.Error -> {:error, :invalid_uri}
  end
end

# end of signature_negotiation.ex
